function code = lbp_op2(vector, patterns)

% pixel : 3 X 3 

%code = find(patterns == vector);
code = strmatch(vector, patterns);

%code = bitshift(vector(1) , 0) +...
%		 bitshift(vector(2) , 1) +...
%		 bitshift(vector(3) , 2) +...
%		 bitshift(vector(4) , 3) +...
%		 bitshift(vector(5) , 4) +...
%		 bitshift(vector(6) , 5) +...
%		 bitshift(vector(7) , 6) +...
%		 bitshift(vector(8) , 7) + 1;

